version: "3"
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment:
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b
    build: ./bootnode
    ports:
      - 30301:30301/udp
    networks:
      ETH:
        ipv4_address: 172.25.0.2

  geth-miner:
    hostname: geth-miner
    depends_on:
      - geth-bootnode
    environment:
      - minerAddress=0x373e1aaE21Ed2A0F249380A151E01429De549b57
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c
      - bootnodeIp=172.25.0.2
    build:
      context: ./miner
      args:
        - privateKey=56a616c5fd6fc2cf06fb864bf4558a3887bf9d88f1025ce879ac3bbcf008fd4d
        - password=miner
    volumes:
      - miner-1:/root/.ethash
    networks: 
      ETH:
        ipv4_address: 172.25.0.3

  geth-miner-2:
    hostname: geth-miner-2
    depends_on:
      - geth-miner
    environment:
      - minerAddress=0x4a1Ef31BD94a70F1707e2E26f6edCEdb3427bED9
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c
      - bootnodeIp=172.25.0.2
    build:
      context: ./miner
      args:
        - privateKey=6fb4652aaed36721463d7c8ba7dcf1cb8074d677de4ccd51e5cda316696a0759
        - password=miner
    volumes:
      - miner-2:/root/.ethash
    networks: 
      ETH:
        ipv4_address: 172.25.0.4

  geth-dev:
     hostname: geth-dev
     depends_on:
       - geth-miner
     environment:
       - minerAddress=0x373e1aaE21Ed2A0F249380A151E01429De549b57
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c
       - bootnodeIp=172.25.0.2
     build:
       context: ./dev-node
       args:
          - privateKey=56a616c5fd6fc2cf06fb864bf4558a3887bf9d88f1025ce879ac3bbcf008fd4d
          - password=miner
     container_name: geth-dev
     ports:
       - 8545:8545
     volumes:
       - dev:/root/.ethash
     networks:
       ETH:
         ipv4_address: 172.25.0.5

  ipfs:
    hostname: ipfs
    build: ./ipfs
    ports:
      - 4001:4001/tcp
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 5001:5001/tcp
    networks:
      ETH:
        ipv4_address: 172.25.0.6

networks:
  ETH:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  miner-1:
  miner-2:
  dev: